config/routes.rb
Rails.application.routes.draw do
 

  root 'pages#home'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :cars, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'location'
      get 'preload'
      get 'preview'
    end

    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]

  end

    resources :renter_reviews, only: [:create, :destroy]
    resources :owner_reviews, only: [:create, :destroy]

    get '/your_trips' => 'reservations#your_trips'
    get '/your_reservations' => 'reservations#your_reservations'

    get 'search' => 'pages#search'

      get 'dashboard' => 'dashboards#index'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :car
  
  has_attached_file :image, styles: { original:"750x750>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


    def create 
        @car = Car.find(params[:car_id])

        if params[:images]
            params[:images].each do |img|
            @car.photos.create(image: img)
            end

            @photos = @car.photos
            redirect_back(fallback_location: request.referer, notice: "Saved..")
            end

    end

    def destroy

        @photo = Photo.find(params[:id])
        @car = @photo.car

        @photo.destroy
        @photos = Photo.where(car_id: car.id)

        respond_to :js
    end

end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
<br></br>

<div class="row">
 <% @photos.each do |photo| %>
   <div class="col-md-4">
    <div class="panel panel-default">
     <div class="panel heading-preview">
      <%= image_tag photo.image.url()%>
    </div>
    <div class="panel-body">
        <span class="pull-right">
        <%= link_to car_photo_path(@car.id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        <%end%>
    </span>

    </div>
   </div>
  </div>
 <%end%>
</div>
<%end%>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")
<% if @car.photos.blank? %>
$('#photo_check').hide();
<%end%>

<% if @car.active && !@car.price.blank? && !@car.listing_name.blank? && !@car.photos.blank? && !@car.location.blank? %>
$('#publish_button').attr('disabled', false)
<%else%>
$('#publish_button').attr('disabled', true)
<%end%>