config/routes.rb
Rails.application.routes.draw do
 

  root 'pages#home'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :cars, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'location'
      get 'preload'
      get 'preview'
    end

    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]

  end

    resources :renter_reviews, only: [:create, :destroy]
    resources :owner_reviews, only: [:create, :destroy]

    get '/your_trips' => 'reservations#your_trips'
    get '/your_reservations' => 'reservations#your_reservations'

    get 'search' => 'pages#search'

      get 'dashboard' => 'dashboards#index'
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  has_many :renter_reviews

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def cover_photo(size)
  if self.photos.length > 0
        self.photos[0].image.url(size)
      else
        "blank.jpg"
      end
  end
    def average_rating
    renter_reviews.count == 0 ? 0 : renter_reviews.average(:star).round(2).to_i
  end
end

app/controllers/cars_controller.rb
#  class CarsController < ApplicationController
#   before_action :set_car, except: [:index, :new, :create]
#   before_action :authenticate_user!, except: [:show]
#   # before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :location, :update]

#   def index
#     @cars = Car.all
#   end

#   def new
#     @car = current_user.cars.build
#   end

#   def create
#       @car = current_user.cars.build(car_params)
#       # @car = current_user.cars.create(params[:car_params])

#     if @car.save
#       redirect_to new_car_path(@car), notice: "Saved..."
#     else
#       flash[:alert] = "Something went wrong.."
#       render :new
#       end
#   end

#   def show
#     @photos = @car.photos
#   end

#   def listing
  
#   end

#   def pricing
    
#   end

#   def description
#   end

#   def photo_upload
#     @photos = @car.photos
#   end

#   def location
#   end

#   def update
#     new_params = car_params
#     new_params = car_params.merge(active: true) if is_car_ready

#     if @car.update(new_params)
#       flash[:notice] = "Saved.."
#     else 
#       flash[:alert] = "Something went wrong.."
#     end
#       redirect_back(fallback_location: request.referer)
#   end

#   private 
#   def set_car 
#     @car = Car.find(params[:id])
#   end

#   # def is_authorised 
#   #   redirect_to root_path, alert: "You don't have permission", unless current_user.id==@car.user_id
#   # end

#   def is_car_ready
#        is_ready = !@car.active && !@car.price.blank? && !@car.listing_name.blank? && !@car.photos.blank? && !@car.location.blank?
#   end

#   def car_params
#     params.require(:car).permit(:listing_name, :car_type, :transmission, :doors_num, :summary, :price, :active)
#   end
# end 

class CarsController < ApplicationController
  before_action :set_car, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    @cars = current_user.cars
  end

  def new
    @car = current_user.cars.build
  end

  def create
    @car = current_user.cars.build(car_params)
    if @car.save
      redirect_to listing_car_path(@car), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos = @car.photos
    @renter_reviews = @car.renter_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @car.photos
  end

  def location
  end

  def update

    new_params = car_params
    new_params = car_params.merge(active: true) if is_ready_car

    if @car.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @car.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @car)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, car)
      check = car.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_car
      @car = Car.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @car.user_id
    end

    def is_ready_car
      !@car.active && !@car.price.blank? && !@car.listing_name.blank? && !@car.photos.blank? && !@car.location.blank?
    end

    def car_params
      params.require(:car).permit(:car_type, :listing_name, :summary, :location, :price, :active)
    end
end

app/helpers/car_helper.rb
module CarHelper
end

app/views/cars/_car_menu.html.erb
<ul class="sidebar-list">

    <li class="sidebar-item">
     <%= link_to "Listing", listing_car_path, class: "sidebar-link active"%>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    </li>

     <li class="sidebar-item">
     <%= link_to "pricing", pricing_car_path, class: "sidebar-link active"%>
     <% if !@car.price.blank?%>
     <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
     <%end%>
    </li>

     <li class="sidebar-item">
     <%= link_to "description", description_car_path, class: "sidebar-link active"%>
     <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    </li>

     <li class="sidebar-item">
     <%= link_to "Photos", photo_upload_car_path, class: "sidebar-link active"%>
        <% if !@car.photos.blank?%>
     <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
     <%end%>
    </li>

     <li class="sidebar-item">
     <%= link_to "Location", location_car_path, class: "sidebar-link active"%>
        <% if !@car.location.blank?%>
     <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
     <%end%>
    </li>
</ul>
<hr/>

<% is_ready = !@car.active && !@car.price.blank? && !@car.listing_name.blank? && !@car.photos.blank? && !@car.location.blank?%>

<%= form_for @car do |f| %>
<%= f.hidden_field :active, value: true %>
<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>



<%end%>

app/views/cars/_cars_list.html.erb
<% cars.each do |car| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag car.cover_photo(:medium) %>
        </div>
        <div class="panel-body">
          <%= link_to car.listing_name, car %><br/>
          $<%= car.price %> - <%= car.car_type %> 
          <div id="star_<%= car.id %>"></div> <%= pluralize(car.average_rating, "stars") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= car.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= car.average_rating %>
      });
    </script>
<% end %>

app/views/cars/create.html.erb
<h1>Car#create</h1>
<p>Find me in app/views/car/create.html.erb</p>

app/views/cars/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'car_menu' %>

  </div>

    <div class="col-md-9">

    <div class="panel panel-default">

    <div class="panel-heading">
    Description
    </div>

                <div class="panel-body">
            <div class="container">        

              <%= form_for @car do |f| %>

            <div class="row">
           <div class="form-group">

            <label>Listing name</label>
            <%=f.text_field :listing_name, placeholder: "What is your listing name", class: "form-control", required: true %> 

             </div>           
      </div>
                   <div class="row">
           <div class="form-group">

            <label>summary</label>
            <%=f.text_area :summary, rows: 5, placeholder: "Summary of your house", class: "form-control", required: true %> 

             </div>           
      </div>
            <div class="text-center">

                <%= f.submit "save", class: "btn btn-form"%>

                
            </div>
               <%end%>
       
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class = "row">
<div class= "col-md-3">
<ul class = "sidebar-list">
<li class="sidebar-item" ><%= link_to "Your Listings", cars_path, class: "sidebar-link active" %> </li>
<li class="sidebar-item" ><%= link_to "Your Reservations", cars_path, class: "sidebar-link active" %> </li>
</ul>

<div class="col-md-9">
 <div class="panel panel-default">
  <div class="panel-heading">
    Lisitngs
</div>
<div class="panel-body">

<% @cars.each do |car|%>
<div class="row">
 <div class="col-md-2">
 <%= image_tag car.cover_photo(:thumb) %>
 </div>
 <div class="col-md-7">
 <h4><%= car.listing_name %></h4>
 </div>
 <div class="col-md-3 right">
    <%= link_to "update", listing_car_path(car), class: "btn btn-form"%>
 </div>        
</div>
<hr/>
<%end%>
</div>
 </div>
</div>
</div>

app/views/cars/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'car_menu' %>

  </div>

    <div class="col-md-9">

    <div class="panel panel-default">

    <div class="panel-heading">
    lisitng
    </div>

                <div class="panel-body">
            <div class="container">        

             <%= form_for @car do |f| %>


    <div class="row">
      <div class="col-md-4 select">
      <div class="form-group">
      <label>Car Type</label>

    <%= f.select :car_type,[["Exotic", "Exotic"],["Sports", "Sports"],["Luxury", "Luxury"]],
       id: "car_type", prompt: "Select...", class: "form-control" %>

      </div>
    </div>

     <div class="col-md-4 select">
      <div class="form-group">
      <label>Transmission</label>

    <%= f.select :transmission,[["Manual", "Manual"],["Automatic", "Automatic"]],
       id: "transmission", prompt: "Select...", class: "form-control" %>

      </div>
    </div>

     <div class="col-md-4 select">
      <div class="form-group">
      <label>Number of Doors</label>

    <%= f.select :doors_num,[["3", 3],["5", 5]],
       id: "doors_num", prompt: "Select...", class: "form-control" %>

      </div>
    </div>


  </div>

    <div> <%= f.submit "Save", class: "btn btn-normal" %> </div>
 
    <%end%>
               
        </div>           
      </div>
    </div>
  </div>
</div>

app/views/cars/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'car_menu' %>

  </div>

    <div class="col-md-9">

    <div class="panel panel-default">

    <div class="panel-heading">
    Location
    </div>

                <div class="panel-body">
            <div class="container">        

            <%= form_for @car do |f| %>

            <div class="row">
           <div class="form-group">

            <label>Location</label>
            <%=f.text_field :location, placeholder: "What is your location", class: "form-control",required: true %> 

            <div class="text-center">

                <%= f.submit "save", class: "btn btn-form"%>
            </div>
            <%end%>

             </div>
            </div>
               
        </div>           
      </div>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class ="panel panel-default">
    <div class ="panel-heading">
        Create you Car
</div>
<div class="panel-body">
    <div class="container">


    <%= form_for @car do |f| %>


    <div class="row">
      <div class="col-md-4 select">
      <div class="form-group">
      <label>Car Type</label>

    <%= f.select :car_type,[["Exotic", "Exotic"],["Sports", "Sports"],["Luxury", "Luxury"]],
       id: "car_type", prompt: "Select...", class: "form-control" %>

      </div>
    </div>

     <div class="col-md-4 select">
      <div class="form-group">
      <label>Transmission</label>

    <%= f.select :transmission,[["Manual", "Manual"],["Automatic", "Automatic"]],
       id: "transmission", prompt: "Select...", class: "form-control" %>

      </div>
    </div>

     <div class="col-md-4 select">
      <div class="form-group">
      <label>Number of Doors</label>

    <%= f.select :doors_num,[["3", 3],["5", 5]],
       id: "doors_num", prompt: "Select...", class: "form-control" %>

      </div>
    </div>


  </div>

    <div> <%= f.submit "List my Car", class: "btn btn-normal" %> </div>
 
    <%end%>



  </div>
 </div>
</div>

app/views/cars/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'car_menu' %>

  </div>

    <div class="col-md-9">

    <div class="panel panel-default">

    <div class="panel-heading">
    Photos
    </div>

                <div class="panel-body">
            <div class="container">        
        <div class="row">

        <div class="col-md-offset-3  col-md-6">

              <%= form_for @car, url: car_photos_path(@car), method: 'post', html: {multipart: true} do |f| %>

              <div class="row">
              <div class="form-group">
              <span class=" btn btn-default btn-file text-babu">
              <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
              <%= file_field_tag "images[]", type: :file, multiple: true %>

                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-default"%>
                </div>

              <%end%>


               </div> 
            </div>

            <div id="photos"> <%= render 'photos/photos_list'%></div>

         </div>
        </div>           
      </div>
    </div>
  </div>
</div>

app/views/cars/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'car_menu' %>

  </div>

    <div class="col-md-9">

    <div class="panel panel-default">

    <div class="panel-heading">
    Pricing
    </div>

                <div class="panel-body">
            <div class="container">        

            <%= form_for @car do |f| %>

            <div class="row">
           <div class="form-group">

            <label>Price</label>
            <%=f.text_field :price, placeholder: "eg: $100", class: "form-control", required: true %> 

            <div class="text-center">

                <%= f.submit "save", class: "btn btn-form"%>
              <%end%>
            </div>
               
        </div>           
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @car.cover_photo(nil), width: "100%" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @car.listing_name %></h1>
        <%= @car.location %>
      </div>
      <div class="col-md-4 text-center">
      
      
      </div>
    </div>
    <hr/>

    <!-- car Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @car.car_type %></div>
          <%= @car.user.fullname %>
      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>About This Listing</h3>
        <p><%= @car.summary %></p>
      </div>
    </div>
    <hr/>


    <!-- Carousel -->
    <div class="row">

      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>

    <!-- REVIEWS -->
    <div class="row">
      <div class="col-md-12">
        <h3>
          <%= pluralize(@renter_reviews.count, "Review") %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%= render "reviews/renter_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>
  


    <!-- GOOGLE MAP -->
    <div class="row">

      <div id="map" style="width: 100%; height: 400px"></div>

      <script src="https://maps.googleapis.com/maps/api/js"></script>
      <script>
          function initialize() {
            var location = {lat: <%= @car.latitude %>, lng: <%= @car.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              center: location,
              zoom: 14
            });

            var marker = new google.maps.Marker({
              position: location,
              map: map
            });

            var infoWindow = new google.maps.InfoWindow({
              content: '<div id="content"><%= image_tag @car.cover_photo(:medium) %></div>'
            });

            infoWindow.open(map, marker);
          }

          google.maps.event.addDomListener(window, 'load', initialize);
      </script>

    </div>
    <hr/>

    <!-- NEAR BY carS -->
    <div class="row">
      <h3>Near by</h3>
      <% for car in @car.nearbys(10) %>
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading preview">
                <%= image_tag car.cover_photo(:medium) %>
              </div>
              <div class="panel-body">
                <%= link_to car.listing_name, car %><br/>
                (<%= car.distance.round(2) %> kms away)
              </div>
            </div>
          </div>
      <% end %>
    </div>

  </div>


  <!-- RIGHT PANEL -->
  <div class="col-md-4">
    <!-- Reservation Form -->
    <%= render 'reservations/form' %>
  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @car.average_rating %>
  });
</script>

app/views/cars/update.html.erb
<h1>Car#update</h1>
<p>Find me in app/views/car/update.html.erb</p>